services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
      POSTGRES_DB: auth
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U gorm -d auth" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - auth-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_auth
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - auth-network

  redis:
    image: redis:alpine
    container_name: redis_auth
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - auth-network

  auth_service:
    build: .
    ports:
      - "50051:50051"
    environment:
      CONFIG_PATH: /app/config/prod.yml
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - auth-network

volumes:
  postgres_data:
  redis_data:


networks:
  auth-network:
    driver: bridge
