name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests on SSH server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          
      - name: Transfer files to remote server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
            --exclude='.git/' \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/project/
            
      - name: Run tests on remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ~/project
            export PATH=$PATH:/usr/local/go/bin

            mv config/local.docker.template.yml config/local.docker.yml
            
            docker-compose -f docker-compose.prod.yml up -d

            sleep 10
            
            make docker-test
            TEST_EXIT_CODE=$?
            
            docker-compose -f docker-compose.prod.yml down -v

            exit $TEST_EXIT_CODE
          EOF
